# Ones Array - An array in which all values are 1

 ####                   A = np.ones(shape, dtype)

- We can define the shape and data-type of ones array
- We can create 1-D, 2-D, 3-D array
- The default data-type is float

- ndim --> to check the dimension of the array
- shape --> to check the shape of the array
- size --> to check the size of the array

In [1]:
import numpy as np

In [5]:
a1 = np.ones(3)       # creating an Ones array, of 1 dimension (still in float format)
print(a1)

[1. 1. 1.]


In [8]:
a1 = np.ones(3, dtype = int)        # creating an Ones array, of 1 dimension, with data-type as integer 
print(a1)

[1 1 1]


In [9]:
type(a1)        # checking the type of o1

numpy.ndarray

In [10]:
a1.ndim        # checking the dimension of a1

1

In [13]:
a2 = np.ones((2,3))    # creating an Ones array, of 2 dimensions
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a2 = np.ones((2,3), dtype=int)   # creating an Ones array, of 2 dimensions, with data-type as integer
print(a2)           

[[1 1 1]
 [1 1 1]]


In [15]:
 a2.shape           # creating the shape of a2

(2, 3)

In [19]:
a3 = np.ones((2,3,4), dtype=int)    # creating an Ones array, of 3 dimensions (2 rows, 3 columns, 4 elements)
print(a3)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [20]:
np.ndim(a3) # or n3.ndim         # checking the dimension of a3

3

In [26]:
np.size(a3) # or n3.size         # checking the numbers of elements in a3

24

In [32]:
percobaan = np.ones(9,bool)
print(percobaan)

[ True  True  True  True  True  True  True  True  True]
